export interface IMonthlyTournamentSchedule {
	formats: Dict<string>;
	times: [number, number][];
}

export interface IRoomTournamentSchedule {
	months: Dict<IMonthlyTournamentSchedule>;
}

/**
 * Hours are in the same timezone as wherever Lanette is running
 */
export const tournamentSchedules: Dict<IRoomTournamentSchedule> = {
	'tournaments': {
		months: {
			'3': {
				formats: {
					'1': 'randombattle',
					'2': 'pu',
					'3': 'ou',
					'4': 'lc',
					'5': 'ubers',
					'6': 'nu',
					'7': 'doublesou',
					'8': 'uu',
					'9': 'ru',
					'10': 'stabmons',
					'11': 'randombattle',
					'12': 'pu',
					'13': 'ou',
					'14': 'lc',
					'15': 'ubers',
					'16': 'nu',
					'17': 'doublesou',
					'18': 'uu',
					'19': 'ru',
					'20': 'almostanyability',
					'21': 'randombattle',
					'22': 'pu',
					'23': 'ou',
					'24': 'lc',
					'25': 'ubers',
					'26': 'nu',
					'27': 'doublesou',
					'28': 'uu',
					'29': 'ru',
					'30': 'omotm',
					'31': 'randombattle',
				},
				times: [[20, 30], [2, 30], [9, 30], [15, 30]],
			},
			'4': {
				formats: {
					'1': 'ou',
					'2': 'monotype',
					'3': 'uu',
					'4': 'doublesou',
					'5': 'ru',
					'6': 'lc',
					'7': 'nu',
					'8': 'monotype',
					'9': 'uu',
					'10': 'doublesou',
					'11': 'ru',
					'12': 'lc',
					'13': 'nu',
					'14': 'ou',
					'15': 'uu',
					'16': 'doublesou',
					'17': 'ru',
					'18': 'lc',
					'19': 'nu',
					'20': 'ou',
					'21': 'monotype',
					'22': 'doublesou',
					'23': 'ru',
					'24': 'lc',
					'25': 'nu',
					'26': 'ou',
					'27': 'monotype',
					'28': 'uu',
					'29': 'ru',
					'30': 'lc',
				},
				times: [[20, 30], [2, 30], [9, 30], [15, 30]],
			},
			'5': {
				formats: {
					'1': 'nu',
					'2': 'ou',
					'3': 'monotype',
					'4': 'uu',
					'5': 'doublesou',
					'6': 'lc',
					'7': 'nu',
					'8': 'ou',
					'9': 'monotype',
					'10': 'uu',
					'11': 'doublesou',
					'12': 'ru',
					'13': 'nu',
					'14': 'ou',
					'15': 'monotype',
					'16': 'uu',
					'17': 'doublesou',
					'18': 'ru',
					'19': 'lc',
					'20': 'ou',
					'21': 'monotype',
					'22': 'uu',
					'23': 'doublesou',
					'24': 'ru',
					'25': 'lc',
					'26': 'nu',
					'27': 'monotype',
					'28': 'uu',
					'29': 'doublesou',
					'30': 'ru',
					'31': 'lc',
				},
				times: [[20, 30], [2, 30], [9, 30], [15, 30]],
			},
		},
	},
	'toursplaza': {
		months: {
			'3': {
				formats: {
					'1': 'Gen 8 UU, Same Type Clause',
					'2': 'Gen 8 Stabmons, - Arena Trap, -Comatose, -Contrary, -Fluffy, -Fur Coat, -Gorilla Tactics, -Huge Power, -Ice Scales, -Illusion, -Imposter, -Innards Out, -Intrepid Sword, -Libero, -Moody, -Neutralizing Gas, -Parental Bond, -Protean, -Pure Power, -Shadow Tag, -Simple, -Stakeout, -Speed Boost, -Water Bubble, -Wonder Guard',
					'3': 'Gen 7 UU, +UUBL',
					'4': 'National Dex, Inverse Mod, -Darmanitan-Galar, -Frosmoth, -Hoopa-U',
					'5': 'Gen 6 Random Battle, Inverse Mod',
					'6': 'Gen 8 Camomons, Same Type Clause',
					'7': 'Gen 8 LC, -Eviolite',
					'8': 'Gen 8 OU, !Dynamax Clause',
					'9': 'Gen 8 Doubles OU, -OU, -UUBL, -UU, -RUBL, -RU, -NU, -NFE, -Drifloon, -Gastly, -Gothita, -Sneasel, -Swirlix, -Vulpix',
					'10': 'OMOTM, Inverse Mod',
					'11': 'Gen 7 PU, +PUBL',
					'12': 'Gen 1 Random Battle, Blitz',
					'13': 'Gen 7 OU, Inverse Mod, -Diggersby, -Hoopa-U',
					'14': 'Gen 8 NU, Same Type Clause',
					'15': 'Gen 7 RU, +RUBL',
					'16': 'Gen 7 Monotype, Gen7Tiershift, -Araquanid, -Avalugg',
					'17': 'Gen 8 NFE, +Doublade',
					'18': 'Gen 2 Random Battle',
					'19': 'Gen 5 Ubers, -Kyogre, -Groudon',
					'20': 'Gen 7 OU, +Genesect, +Deoxys-Speed',
					'21': 'Gen 6 Anything Goes, -Darkrai, -Klefki',
					'22': 'Gen 7 Mix and Mega, -Uber, -OU, -UUBL, -UU, -RUBL, -RU, -NUBL, -NU, -PUBL, -PU',
					'23': 'Gen 6 Battle Spot Singles, inverse mod',
					'24': 'Gen 4 UU, Blitz',
					'25': 'Gen 7 PU, Same Type Clause, +PUBL',
					'26': 'Gen 8 NU, inverse mod',
					'27': 'Gen 7 RU,  - Arena Trap, -Comatose, -Contrary, -Fluffy, -Fur Coat, -Huge Power, -Illusion, -Imposter, -Innards Out, -Moody, -Parental Bond, -Protean, -Pure Power, -Shadow Tag, -Simple, -Stakeout, -Speed Boost, -Water Bubble, -Wonder Guard',
					'28': 'omotm2',
					'29': 'Gen 8 CAP',
					'30': 'Gen 7 Doubles OU, -Drizzle, -Drought, -Sand Stream',
					'31': 'Gen 5 UU, Same Type Clause',
				},
				times: [[5, 30], [12, 30], [18, 30], [23, 30]],
			},
			'4': {
				formats: {
					'1': 'randombattle@@@Inverse Mod,gen8camomons',
					'2': 'gen7ubers',
					'3': 'ou@@@!Dynamax Clause',
					'4': 'nu',
					'5': 'stabmons@@@!Obtainable Abilities',
					'6': 'gen8nationaldexag',
					'7': 'doublesou@@@-OU,-UUBL,-UU,-RUBL,-RU,-NUBL,-NU,-PUBL,-PU',
					'8': 'omotm',
					'9': 'mixandmega@@@STABmons Move Legality,gen8camomons',
					'10': 'randomdoublesbattle',
					'11': 'gen7ou@@@-Drizzle,-Sand Stream,-Drought',
					'12': 'gen4lc',
					'13': 'gen7nu@@@+NUBL,+Gigalith',
					'14': 'uu',
					'15': 'ubers@@@!Obtainable Abilities',
					'16': 'gen7battlefactory',
					'17': 'ru@@@+RUBL,!Obtainable Abilities',
					'18': 'gen5ou',
					'19': 'doublesou@@@Dynamax Clause',
					'20': 'battlestadiumsingles',
					'21': 'gen7randombattle@@@Inverse Mod',
					'22': 'omotm2',
					'23': 'lc@@@+LC Uber',
					'24': 'pu',
					'25': 'gen7uu@@@gen7tiershift',
					'26': 'nfe',
					'27': 'cap@@@STABmons Move Legality,!Obtainable Abilities',
					'28': 'monotyperandombattle',
					'29': 'doublesubers@@@Same Type Clause',
					'30': 'gen7ou',
				},
				times: [[5, 30], [12, 30], [18, 30], [23, 30]],
			},
		},
	},
};
