/**
 * Hours are in the same timezone as wherever Lanette is running
 */
const schedules: Dict<{months: Dict<Dict<string> | undefined>, times: [number, number][]}> = {
	'nfe': {
		months: {
			'11': {
				'daily': 'gen8nfe',
			},
		},
		times: [[10, 0], [15, 0], [20, 0]],
	},
	'tournaments': {
		months: {
			'11': {
				'1': 'gen7randombattle',
				'2': 'gen7pu',
				'3': 'gen7ou',
				'4': 'gen7lc',
				'5': 'gen7ubers',
				'6': 'gen7nu',
				'7': 'gen7doublesou',
				'8': 'gen7uu',
				'9': 'gen7ru',
				'10': 'gen7almostanyability',
				'11': 'gen7randombattle',
				'12': 'gen7pu',
				'13': 'gen7ou',
				'14': 'gen7lc',
				'15': 'gen7ubers',
				'16': 'gen7nu',
				'17': 'gen7doublesou',
				'18': 'gen7uu',
				'19': 'gen7ru',
				'20': 'gen7mixandmega',
				'21': 'gen7randombattle',
				'22': 'gen7pu',
				'23': 'gen7ou',
				'24': 'gen7lc',
				'25': 'gen7ubers',
				'26': 'gen7nu',
				'27': 'gen7doublesou',
				'28': 'gen7uu',
				'29': 'gen7ru',
				'30': 'omotm',
			},
		},
		times: [[2, 30], [9, 30], [15, 30], [20, 30]],
	},
	'toursplaza': {
		months: {
			'11': {
				'1': '[Gen 7] RU@@@+RUBL,-Drought,-Trick Room',
				'2': '[Gen 8] 2v2 Doubles@@@Same Type Clause,-Drizzle,-Drought,-Sand Stream,-Snow Warning',
				'3': '[Gen 7] LC@@@+Aipom,+Cutiefly,+Drifloon,+Gothita,+Meditite,+Misdreavus,+Murkrow,+Porygon,+Swirlix,+Trapinch,+Vulpix,+Wingull,+Yanma,+Sonic Boom',
				'4': '[Gen 7] Ubers@@@+Rayquaza-Mega,!Mega Rayquaza Clause',
				'5': '[Gen 7] Almost Any Ability@@@gen7tiershift,-Thick Club,-Absol,-Metagross',
				'6': '[Gen 6] OU@@@+Greninja,+Hoopa-Unbound',
				'7': '[Gen 7] PU@@@STABmons Move Legality,-Acupressure,-Belly Drum,-Chatter,-Extreme Speed,-Geomancy,-Lovely Kiss,-Shell Smash,-Shift Gear,-Spore,-Thousand Arrows',
				'8': '[Gen 7] Doubles OU@@@Inverse Mod',
				'9': '[Gen 7] Anything Goes@@@-Rayquaza,-Uber,-OU,-UUBL,-UU,-RUBL,-RU,-NUBL,-NU,-PUBL,-PU,-ZU,-NFE,-LC Uber',
				'10': '[Gen 8] NFE@@@Ignore Illegal Abilities,-Comatose,-Contrary,-Fluffy,-Fur Coat,-Huge Power,-Illusion,-Imposter,-Innards Out,-Parental Bond,-Protean,-Pure Power,-Simple,-Speed Boost,-Stakeout,-Water Bubble,-Wonder Guard',
				'11': '[Gen 7] OU@@@-Greninja-Ash,-Toxapex,-Magearna,-Heatran,-Landorus-T',
				'12': '[Gen 7] Mix and Mega@@@-Uber,-OU,-UUBL,-UU,-RUBL,-RU',
				'13': '[Gen 7] Balanced Hackmons@@@Inverse Mod',
				'14': '[Gen 7] ZU@@@gen7camomons',
				'15': '[Gen 7] Random Battle',
				'16': '[Gen 7] Almost Any Ability@@@Same Type Clause,Stabmons Move Legality,-OU,-UUBL,-UU,-RUBL,-RU,-Extreme Speed,-Geomancy,-Belly Drum,-Shell Smash,-Aegislash,-Genesect,-Landorus,-Naganadel,-Metagross-Mega',
				'17': '[Gen 7] Battle Factory@@@!Team Preview',
				'18': '[Gen 7] Balanced Hackmons',
				'19': '[Gen 8] 2V2 Doubles',
				'20': '[Gen 7] Mix and Mega@@@-OU,-UUBL,-UU,-RUBL,-RU,-NUBL,-NU,-PUBL,-PU',
				'21': '[Gen 7] Doubles OU@@@-Uber,-OU,-UUBL,-UU,-RUBL,-RU,-NUBL,-NU,-PUBL,-PU,-ZU,-NFE,-LC Uber',
				'22': 'omotm',
				'23': '[Gen 7] BSS Factory@@@gen7tiershift,gen7camomons',
				'24': 'omotm',
				'25': '[Gen 7] Ubers',
				'26': '[Gen 7] Monotype@@@gen7tiershift',
				'27': '[Gen 7] PU@@@+Audino-Mega,+Glalie-Mega,+Incineroar,+Silvally-Steel',
				'28': '[Gen 7] Doubles OU@@@STABmons Move Legality,-Acupressure,-Belly Drum,-Chatter,-Extreme Speed,-Geomancy,-Lovely Kiss,-Shell Smash,-Shift Gear,-Spore,-Thousand Arrows',
				'29': '[Gen 7] UU@@@Inverse Mod',
				'30': '[Gen 7] LC@@@Ignore Illegal Abilities,-Comatose,-Contrary,-Fluffy,-Fur Coat,-Huge Power,-Illusion,-Imposter,-Innards Out,-Parental Bond,-Protean,-Pure Power,-Simple,-Speed Boost,-Stakeout,-Water Bubble,- Wonder Guard',
			},
		},
		times: [[5, 30], [12, 30], [18, 30], [23, 30]],
	},
};

export = schedules;
