import type { IRoomTournamentSchedule } from "./types/tournaments";

/**
 * Hours are in the same timezone as wherever Lanette is running
 */
export const tournamentSchedules: Dict<IRoomTournamentSchedule> = {
	'tournaments': {
		months: {
			'5': {
				formats: {
					'1': 'ubers',
					'2': 'monotype',
					'3': 'ou',
					'4': 'lc',
					'5': 'uu',
					'6': 'pu',
					'7': 'ru',
					'8': 'nu',
					'9': 'doublesou',
					'10': 'ubers',
					'11': 'monotype',
					'12': 'ou',
					'13': 'lc',
					'14': 'uu',
					'15': 'pu',
					'16': 'ru',
					'17': 'nu',
					'18': 'doublesou',
					'19': 'ubers',
					'20': 'monotype',
					'21': 'ou',
					'22': 'lc',
					'23': 'uu',
					'24': 'pu',
					'25': 'ru',
					'26': 'nu',
					'27': 'doublesou',
					'28': 'ubers',
					'29': 'monotype',
					'30': 'ou',
					'31': 'lc',
				},
				times: [[2, 30], [9, 30], [15, 30], [20, 30]],
			},
		},
	},
	'toursplaza': {
		months: {
			'5': {
				formats: {
					'1': 'monotype',
					'2': 'nationaldexmonotype',
					'3': 'uu@@@same type clause',
					'4': 'ru@@@same type clause',
					'5': 'nu@@@same type clause',
					'6': 'pu@@@same type clause',
					'7': 'lc@@@same type clause',
					'8': 'gen1ou@@@same type clause',
					'9': 'gen2ou@@@same type clause',
					'10': 'gen3ou@@@same type clause',
					'11': 'gen4ou@@@same type clause',
					'12': 'gen5monotype',
					'13': 'gen6monotype',
					'14': 'gen7monotype',
					'15': 'ubers@@@same type clause',
					'16': 'monotype@@@inverse mod',
					'17': 'tier shift@@@inverse mod',
					'18': 'battlefactory@@@inverse mod',
					'19': 'almostanyability@@@inverse mod',
					'20': 'camomons@@@inverse mod',
					'21': 'nfe@@@inverse mod',
					'22': 'balancedhackmons@@@inverse mod',
					'23': 'sharedpower@@@inverse mod',
					'24': 'stabmons@@@inverse mod',
					'25': 'zu@@@inverse mod',
					'26': '1v1@@@inverse mod',
					'27': 'randombattle@@@inverse mod',
					'28': 'doublesou@@@inverse mod',
					'29': 'gen6ou@@@inverse mod',
					'30': 'gen7ou@@@inverse mod',
					'31': 'ou@@@inverse mod',
				},
				times: [[5, 30], [12, 30], [18, 30], [23, 30]],
			},
		},
	},
};
